.\" Most of the text in this manual page is either
.\" copied verbatim or derived from the various RFCs
.\" or the Wikipedia article listed in the SEE ALSO
.\" section.  That article itself is largely copied
.\" verbatim or derived from the various RFCs, and
.\" licensed under the Creative Commons
.\" Attribution-Share-Alike License 3.0
.\" (https://creativecommons.org/licenses/by-sa/3.0/).
.\"
.\" As far as the markup here is concerned, please
.\" feel free to take this file an do with it what you
.\" please, so long as your lawyers agree that this is
.\" allowed by the original sources' licensing terms.
.\" I am not a lawyer, and know better to play one on
.\" the internet.
.\"
.\" Jan Schaumann <jschauma@netmeister.org>, July 2021
.Dd December 12, 2023
.Dt httpstatus 7
.Os
.Sh NAME
.Nm httpstatus
.Nd HTTP status codes
.Sh DESCRIPTION
This manual page documents the HTTP status codes
commonly issued by a web server in response to a
client request.
The status codes in this manual page are based on the
information found in RFC7231 unless otherwise noted.
.Pp
HTTP status codes fall into one of five classes,
identified by the first digit as follows:
.Bl -tag -width XX
.It 1xx (Informational)
The request was received, continuing process.
.It 2xx (Successful)
The request was successfully received, understood, and accepted.
.It 3xx (Redirection)
Further action needs to be taken in order to complete
the request.
.It 4xx (Client Error)
The request contains bad syntax or cannot be
fulfilled.
.It 5xx (Server Error)
The server failed to fulfill an apparently valid
request.
.El
.Sh 1xx STATUS CODES
.Bl -tag -width XX
.It 100 Continue
The server has received the initial part of the
request and the client should proceed to send the
remainder.
.It 101 Switching Protocols
The server agrees to the client's request to switch
protocols via the RFC7230 "Upgrade" header.
.It 102 Processing
The server has has accepted the complete request,
but has not yet completed it.
(WebDAV; RFC2518)
.It 103 Early Hints
The server is likely to send a final response with the
header fields included in the informational response.
(RFC8297)
.El
.Sh 2xx STATUS CODES
.Bl -tag -width XX
.It 200 Ok
The request has succeeded.
.It 201 Created
The request has been fulfilled and has resulted in one
or more new resources being created.
.It 202 Accepted
The request has been accepted for processing, but the
processing has not been completed.
.It 203 Non-Authoritative Information
The request was successful but the enclosed payload has
been modified from that of the origin server's 200
(OK) response by a transforming proxy.
.It 204 \&No Content
The server has successfully fulfilled the request;
there is no additional content to send in the response
payload body.
.It 205 Reset Content
The server has fulfilled the request; the client
should reset its document view.
.It 206 Partial Content
The server is successfully fulfilling a range request
for the target resource based on the client's "Range"
header. (RFC7233)
.It 207 Multi-Status
Multiple resources were to be affected by the COPY,
but errors on some of them prevented the operation
from taking place. (WebDAV; RFC4918)
.It 208 Already Reported
Indicates that members of multiple bindings from a previous
multi-status response are not repeated.
(WebDAV; RFC5842)
.It 226 IM Used
The server has fulfilled a GET request for the
resource, and the response is a representation of the
result of one or more instance- manipulations applied
to the current instance.
(RFC3229)
.El
.Sh 3xx STATUS CODES
.Bl -tag -width XX
.It 300 Multiple Choices
The target resource has more than one representation
which the client may choose from via Content
Negotiation.
.It 301 Moved Permanently
The target resource has been assigned a new permanent
URI and any future references to this resource ought
to use one of the enclosed URIs.
.It 302 Found
The target resource resides temporarily under a
different URI.
.It 303 See Other
The server is redirecting the user agent to a
different resource, as indicated by a URI in the
Location header field.
.It 304 Not Modified
A conditional GET or HEAD request has been received
and would have resulted in a 200 (OK) response if it
were not for the fact that the condition evaluated to
false.
(RFC7232)
.It 305 Use Proxy
The requested resource MUST be accessed through the
proxy given by the Location field. (RFC2616)
Deprecated due to security concerns regarding in-band
configuration of a proxy.
.It 306 Switch Proxy
No longer used.
Originally generated by a proxy server to indicate
that the client or proxy should use the information in
the accompanying 'Set- proxy' header to choose a proxy
for subsequent requests.
.It 307 Temporary Redirect
The target resource resides temporarily under a
different URI and the user agent MUST NOT change the
request method if it performs an automatic redirection
to that URI.
.It 308 Permanent Redirect
The target resource has been assigned a new permanent
URI and any future references to this resource ought
to use one of the enclosed URIs.
(RFC7538)
.El
.Sh 4xx STATUS CODES
.Bl -tag -width XX
.It 400 Bad Request
The server cannot or will not process the request due
to something that is perceived to be a client error
(e.g., malformed request syntax, invalid request
message framing, or deceptive request routing).
.It 401 Unauthorized
The request has not been applied because it lacks
valid authentication credentials for the target
resource.
.It 402 Payment Required
Reserved for future use.
.It 403 Forbidden
The server understood the request but refuses to
authorize it.
.It 404 Not Found
The origin server did not find a current
representation for the target resource or is not
willing to disclose that one exists.
.It 405 Method Not Allowed
The method received in the request-line is known by
the origin server but not supported by the target
resource.
.It 406 Not Acceptable
The target resource does not have a current
representation that would be acceptable to the user
agent, such as due to the client's "Accept" header.
.It 407 Proxy Authentication Required
The client needs to authenticate itself in order to
use a proxy.
(RFC7235)
.It 408 Request Timeout
The server did not receive a complete request message
within the time that it was prepared to wait.
.It 409 Conflict
The request could not be completed due to a conflict
with the current state of the target resource.
.It 410 Gone
Access to the target resource is no longer available
at the origin server; this condition is likely to be
permanent.
.It 411 Length Required
The server refuses to accept the request without a
defined Content-Length.
.It 412 Precondition Failed
One or more conditions given in the request header
fields evaluated to false when tested on the server.
(RFC7232)
.It 413 Payload Too Large
The server is refusing to process a request because
the request payload is larger than the server is
willing or able to process.
.It 414 URI Too Long
The server is refusing to service the request because
the request-target is longer than the server is
willing to interpret.
.It 415 Unsupported Media Type
The origin server is refusing to service the request
because the payload is in a format not supported by
this method on the target resource.
.It 416 Range Not Satisfiable
None of the ranges in the request's Range header field
overlap the current extent of the selected resource or
the set of ranges requested has been rejected due to
invalid ranges or an excessive request of small or
overlapping ranges.
(RFC7233)
.It 417 Expectation Failed
The expectation given in the request's Expect header
field could not be met by at least one of the inbound
servers.
.It 418 I'm a teapot
An attempt to brew coffee was made, even though the
target is a teapot.
(RFC2324)
.It 421 Misdirected Request
The request was directed at a server that is not able
to produce a response.
(RFC7540)
.It 422 Unprocessable Entity
The server understands the content type of the request
entity and the syntax of the request entity is
correct, but was unable to process the contained
instructions.
(WebDAV; RFC4918)
.It 423 Locked
The source or destination resource of a method is
locked.
(WebDAV; RFC4918)
.It 424 Failed Dependency 
The method could not be performed on the resource
because the requested action depended on another
action and that action failed.
(WebDAV; RFC4918)
.It 425 Too Early
The server is unwilling to risk processing a request
that might be replayed.
(RFC8470)
.It 426 Upgrade Required
The server refuses to perform the request using the
current protocol but might be willing to do so after
the client upgrades to a different protocol.
.It 428 Precondition Required
The origin server requires the request to be
conditional.
(RFC6585)
.It 429 Too Many Requests
The user has sent too many requests in a given amount
of time.
(RFC6585)
.It 431 Request Header Fields Too Large
The server is unwilling to process the request because
its header fields are too large.
(RFC6585)
.It 451 Unavailable For Legal Reasons
The server is denying access to the resource as a
consequence of a legal demand.
(RFC7725)
Named after Ray Bradbury's "Fahrenheit 451".
.El
.Sh 5xx STATUS CODES
.Bl -tag -width XX
.It 500 Internal Server Error
The server encountered an unexpected condition that
prevented it from fulfilling the request.
.It 501 Not Implemented
The server does not support the functionality required
to fulfill the request. 
.It 502 Bad Gateway
The server, while acting as a gateway or proxy,
received an invalid response from an inbound server it
accessed while attempting to fulfill the request.
.It 503 Service Unavailable
The server is currently unable to handle the request
due to a temporary overload or scheduled maintenance,
which will likely be alleviated after some delay.
.It 504 Gateway Timeout
The server, while acting as a gateway or proxy, did
not receive a timely response from an upstream server
it needed to access in order to complete the request.
.It 505 HTTP Version Not Supported
The server does not support, or refuses to support,
the major version of HTTP that was used in the request
message. 
.It 506 Variant Also Negotiates
The server's chosen variant resource is configured to
engage in transparent content negotiation itself, and
is therefore not a proper end point in the negotiation
process.
(RFC2295)
.It 507 Insufficient Storage
The method could not be performed on the resource
because the server is unable to store the
representation needed to successfully complete the
request.
(WebDAV; RFC4918)
.It 508 Loop Detected
The server terminated an operation because it
encountered an infinite loop while processing a
request with "Depth: infinity". 
(WebDAV; RFC5842)
.It 510 Not Extended
The policy for accessing the resource has not been met
in the request.
(RFC2774)
.It 511 Network Authentication Required
The client needs to authenticate to gain network
access.
(RFC6585)
.El
.Sh NON STANDARD HTTP STATUS CODES
In addition to the above, several HTTP server or proxy
implementations include custom status codes,
particularly in the 4xx and 5xx classes.
.Bl -tag -width XX
.It 000 (AWS ELB)
Used by AWS Elastic Load Balancing with HTTP/2 GOAWAY
frame if the compressed length of any of the headers
exceeds 8K bytes or if more than 10K requests are
served through one connection exceeds 10,000.
.It 000 (curl)
Used by
.Xr curl 1
to indicate a failed execution.
.It 000 Client-Side Abort (Akamai LDS)
Used by Akamai Log Delivery Services if a download was
terminated by the end-user before the edge server is
able to send back the response header.
.It 000 (Looker Studio)
No HTTP code was received.
.It 218 This is fine (Apache httpd)
A catch-all error condition displayed instead of a 4xx
or 5xx error, allowing the passage of message bodies
through the server when the
.Ar ProxyErrorOverride
setting is enabled.
.It 299 Deprecated (Linode)
The request was successful, but involved a deprecated
endpoint.
.It 419 Page Expired (Laravel)
A CSRF Token is missing, expired, or cannot be verified.
.It 430 Shopify Security Rejection (Shopify)
The request was deemed malicious.
.It 440 Login Time-out (Microsoft IIS)
The client's session has expired and must log in again.
.It 444 \&No Response (nginx)
Used by the ngx_http_rewrite_module to instruct
the server to close the connection without sending a
response header.
.It 449 Retry With Status Code (Microsoft IIS)
The request cannot be satisfied because insufficient
information was provided by the client.
.It 450 Blocked by Windows Parental Controls (Microsoft)
Windows Parental Controls are turned on and are
blocking access to the requested webpage.
.It 451 Redirect (Microsoft Exchange)
Used by Microsoft Exchange ActiveSync to indicate that
the client is attempting to connect to the wrong
server, or if there is a more efficient server to use
to reach the user's mailbox
.It 460 (AWS ELB)
The client closed the connection with the load balancer
before the idle timeout period elapsed.
.It 463 (AWS ELB)
The load balancer received an X-Forwarded-For request
header with too many IP addresses.
.It 464 (AWS ELB)
Incompatible protocol versions between the client and
the origin server.
.It 492 User Access Forbidden (Akamai EAA)
The client is not authorized to access the application.
.It 493 Unsupported Browser (Akamai EAA)
The client did not send a Server Name Identification
(SNI) in the TLS handshake.
.It 494 Request Header Too Large (nginx)
The client sent too large a request or too long a
header line.
.It 494 Request Header Or Cookie Too Large (Akamai EAA)
An HTTP Request Header is bigger than the configured
buffer value.
.It 498 Invalid Token (Esri)
Used by the Esri ArcGIS Server to indicate an expired
or otherwise invalid token.
.It 495 SSL Certificate Error (nginx)
The client has provided an invalid client certificate.
.It 496 496 SSL Certificate Required (nginx)
A client certificate is required but was not provided.
.It 497 HTTP Request Sent to HTTPS Port (nginx)
The client has made an HTTP request to an HTTPS port.
.It 499 Client Closed Request (nginx)
The client has closed the request before the server
could send a response.
.It 499 Token Required (Esri)
Used by the Esri ArcGIS Server to indicate that a
token is required but was not submitted.
.It 503 Loop Detected (Fastly)
A request appears to originate from the same Fastly
service that it is trying to invoke, or the request
has transited too many Fastly servers.
.It 509 Bandwidth Limit Exceeded (Apache httpd / cPanel)
The server has exceeded the bandwidth specified
by the server administrator.
.It 520 Web Server Returned an Unknown Error (Cloudflare)
The origin server returned an empty, unknown, or
unexpected response to Cloudflare.
.It 521 Web Server Is Down (Cloudflare)
The origin server refused connections.
.It 522 Connection Timed Out (Cloudflare)
Time out when contacting the origin server.
.It 523 Origin Is Unreachable (Cloudflare)
The origin server was unreachable.
.It 524 A Timeout Occurred (Cloudflare)
After a successful TCP connection to the origin server
the HTTP response timed out.
.It 525 SSL Handshake Failed (Cloudflare)
TLS handshake failure with the origin server.
.It 526 Invalid SSL Certificate (Cloudflare / Cloud Foundry)
Unable to validate the origin server's TLS certificate.
.It 527 Railgun Error (Cloudflare)
Connection interrupted between Cloudflare and the
origin server's Railgun server.
.It 529 Site is overloaded (Qualys SSLabs)
API service is overloaded.
.It 530 Internal Edgio Error (Edgio)
An unexpected error.
.It 530 (Cloudflare)
Used by Cloudflare as a generic error status code.
More details can be found in the accompanying HTML
body describing a 1XXX error code.
.It 530 Site is frozen (Pantheon)
A site that has been frozen due to inactivity.
.It 530 Origin DNS Error (Shopify)
Cloudflare can't resolve the requested DNS record.
.It 531 Project Upstream Connection Error (Edgio)
Unable to establish a connection to the origin server.
.It 532 Project Response Too Large (Edgio)
A returned a response size was greater than the allowed maximum.
.It 533 Project Upstream TLS Error (Edgio)
Unable to establish a TLS connection to the origin.
.It 534 Project Error (Edgio)
The project’s serverless code has failed unexpectedly
or has issued a malformed response.
.It 535 Unknown Project (Edgio)
Missing or mismatching Host header.
.It 536 Project HTTP Response Timeout (Edgio)
Time out when contacting the origin server.
.It 537 Project DNS Resolution Error (Edgio)
The proxy was unable to resolve the host name.
.It 538 Project Request Loop (Edgio)
The request went through too many Edgio servers.
.It 539 Project Timeout (Edgio)
The project's serverless code did not respond in time.
.It 540 Temporarily Disabled (Shopify)
The requested endpoint has been temporarily disabled.
.It 540 Connectivity Disrupted (Akamai EAA)
The connector does not have dial-out connections to
either the data POP for the application or access to
the directory.
.It 540 Out of Memory (Edgio)
The project's serverless code caused an out-of-memory
situation.
.It 541 Edgio Out of Workers (Edgio)
Traffic was too high to be scheduled for processing
within the scheduling timeout.
.It 542 Internal Database Error (Akamai EAA)
The data POP cannot reach the authentication database.
.It 542 Project Header Overflow (Edgio)
The project's request or response had too many HTTP
headers.
.It 543 IdP Communication Error (Akamai EAA)
The data POP cannot reach the IdP or directory service.
.It 543 Global Upstream Timeout (Edgio)
The request failed to propagate between Edgio edge and
the global POP.
.It 544 Management Communication Error (Akamai EAA)
The Login/Authentication POP cannot reach the
management login manager.
.It 544 Invalid Host Header (Edgio)
The Host header is not a valid domain name.
.It 545 Authentication Internal Error (Akamai EAA)
The data POP cannot resolve/reach the authentication
database.
.It 545 Edgio Component Not Ready (Edgio)
An unprepared Edgio component received traffic.
.It 546 Unknown Application (Akamai EAA)
The Login/Authentication POP does not have the
application configuration.
.It 546 Edgio Global POP TLS Error (Edgio)
An error occurred negotiating a secure TLS connection
with the Edgio global POP.
.It 547 Edgio Global POP \&No HTTP Response (Edgio)
No HTTP response from the global POP.
.It 548 Invalid Response (Akamai EAA)
The response received from the login server could not
be validated via back-channel request from the cloud
proxy to the login server.
.It 548 Edgio Global POP DNS Resolution Error (Edgio)
Failure to resolve the global POP's host name through
the DNS.
.It 549 Authentication Gateway Error (Akamai EAA)
The Login service cannot reach directories to complete
the authentication process.
.It 552 Application Unreachable (Akamai EAA)
The application service is not reachable from
connector.
.It 553 Directory Service Error (Akamai EAA)
A directory service error during Kerberos
authentication.
.It 554 Authentication Token Error (Akamai EAA)
The Kerberos token is not accepted by application.
.It 555 Application does not support Kerberos (Akamai EAA)
No negotiate option found in 401 challenge.
.It 556 Unexpected Authentication Challenge (Akamai EAA)
Encountered a 401 challenge on a URI not configured as
login URI.
.It 557 KDC Unreachable (Akamai EAA)
The KDC is unreachable.
.It 558 Connection Limit Stop: Service Concurrent Connections Exceeded (Akamai EAA)
A user has established too many WebSocket connections.
.It 559 Connection Limit Stop: Service Concurrent Connections Exceeded (Akamai EAA)
A user has established too many WebSocket connections.
.It 561 Invalid NTLM Challenge (Akamai EAA)
The connector received an invalid NTLM challenge from
server.
.It 561 Unauthorized (AWS ELB)
IdP could not authenticate the user.
.It 562 Credential Error (Akamai EAA)
Unable to encrypt or decrypt NTLM credentials.
.It 598 Network Read Timeout Error
Used by some HTTP proxies to signal a network read
timeout behind the proxy to a client in front of the
proxy.
.It 599 Network Connect Timeout Error
Used by some HTTP proxies to signal a network connect
timeout behind the proxy to a client in front of the
proxy.
.It 600 (Akamai)
Used by Akamai to indicate various invalid headers.
.It 783 Unexpected Token (Shopify)
The request includes a JSON syntax error.
.It 893 (Edgio)
Used by Edgio when load balancing high volume traffic
for a specific asset within a POP.
.El
.Sh SEE ALSO
RFC2324,
RFC2518,
RFC2616,
RFC3229,
RFC4918,
RFC5842,
RFC6585,
RFC7230,
RFC7231,
RFC7232,
RFC7233,
RFC7538,
RFC7540
.Pp
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
.Sh HISTORY
This list of HTTP status codes was originally compiled
into a manual page by
.An Jan Schaumann
.Aq jschauma@netmeister.org
in July 2021.
